/**
 * Obsidian Knowledge-Vault & Subdomain Playbook Exporter Engine
 * Domain Folders -> Subdomain Playbook Files (.md) -> ZIP & Single Markdown
 */

import { getLivingTaxonomy } from "./taxonomy.js";

const BRAND_URL = "https://reelanalyzer.manikanta.co.in/";
const BRAND_NAME = "Reel Analyzer";

/**
 * Sanitizes a string for safe filesystem folder/file naming
 */
function sanitizeFileName(str) {
  if (!str) return "General";
  return str.replace(/[\\/:*?"<>|]/g, "_").trim();
}

/**
 * Generates an anchor slug for markdown Table of Contents
 */
function slugify(str) {
  if (!str) return "insight";
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

/**
 * Builds the complete Markdown content for a single Subdomain Playbook
 */
export function buildSubdomainPlaybookMarkdown(domain, subdomain, reels) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const allTags = [...new Set(reels.flatMap(r => (r.tags || "").split(/[,\s]+/).filter(t => t.startsWith("#"))))];

  let md = `---
domain: "${domain}"
subdomain: "${subdomain}"
total_insights: ${reels.length}
tags: [${allTags.map(t => `"${t}"`).join(", ")}]
vault: "${BRAND_NAME}"
exported_at: "${dateStr}"
source: "${BRAND_URL}"
---

# 📂 ${domain} > ${subdomain}

> 🧠 **${BRAND_NAME} Knowledge Playbook**
> Total Curated Insights: **${reels.length} Reels**

---

## 📑 Table of Contents
`;

  reels.forEach((r, idx) => {
    const num = idx + 1;
    const title = r.subject || `Insight #${num}`;
    const anchor = `${num}-${slugify(title)}`;
    const utility = r.personalUtility ? ` — *💡 ${r.personalUtility.slice(0, 90)}${r.personalUtility.length > 90 ? "..." : ""}*` : "";
    md += `${num}. [${title}](#${anchor})${utility}\n`;
  });

  md += `\n---\n\n`;

  reels.forEach((r, idx) => {
    const num = idx + 1;
    const title = r.subject || `Insight #${num}`;
    const anchor = `${num}-${slugify(title)}`;

    md += `## ${num}. ${title} <a id="${anchor}"></a>\n\n`;
    if (r.personalUtility) {
      md += `> 💡 **Key Takeaway:** ${r.personalUtility}\n`;
    }
    if (r.entities) {
      md += `> 🛠️ **Tools & Tech:** \`${r.entities}\`\n`;
    }
    if (r.tags) {
      md += `> 🏷️ **Tags:** ${r.tags}\n`;
    }
    md += `> 🔗 **Original Reel:** [Watch on Instagram](${r.url || ""})\n\n`;

    md += `### 📖 Summary & Directives\n\n${r.summary || "No summary available."}\n\n---\n\n`;
  });

  md += `<br>\n\n<div align="center">\n  <sub>Generated by <strong><a href="${BRAND_URL}">${BRAND_NAME}</a></strong> • Turn Instagram Reels into Reusable Knowledge</sub>\n</div>\n`;

  return md;
}

/**
 * Builds the Master Index file (00_Master_Index.md) for the Obsidian Vault
 */
export function buildMasterIndexMarkdown(allReels, groupedTree) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const totalDomains = Object.keys(groupedTree).length;

  let md = `---
vault: "${BRAND_NAME} Knowledge Base"
total_reels: ${allReels.length}
total_domains: ${totalDomains}
exported_at: "${dateStr}"
source: "${BRAND_URL}"
---

# 📚 ${BRAND_NAME} Knowledge Vault (Master Index)

> 🧠 **Personal Knowledge Base**
> Exported on **${dateStr}** • Total Insights: **${allReels.length} Reels** across **${totalDomains} Domains**

---

## 🌐 Knowledge Domains & Subdomains

`;

  for (const [domain, subdomains] of Object.entries(groupedTree)) {
    const cleanDom = sanitizeFileName(domain);
    let totalDomReels = 0;
    Object.values(subdomains).forEach(arr => { totalDomReels += arr.length; });

    md += `### 📁 ${domain} (${totalDomReels} Reels)\n\n`;

    for (const [subdomain, reels] of Object.entries(subdomains)) {
      const cleanSub = sanitizeFileName(subdomain);
      const filePath = `${cleanDom}/${cleanSub}.md`;
      md += `- 📄 **[[${filePath}|${subdomain}]]** (${reels.length} Reels)\n`;

      reels.forEach((r, idx) => {
        const title = r.subject || `Insight #${idx + 1}`;
        md += `  - [${title}](${encodeURI(filePath)}#${idx + 1}-${slugify(title)})\n`;
      });
    }
    md += `\n`;
  }

  md += `---\n\n## 🛠️ Extracted Tools & Tech Stack\n\n`;
  md += `| Tool / Resource | Category | Mentioned In |\n|---|---|---|\n`;

  const allEntities = allReels
    .flatMap((r) => (r.entities || "").split(",").map((e) => e.trim()))
    .filter((e) => e && e.toLowerCase() !== "none" && e.length > 1);
  const uniqueEntities = [...new Set(allEntities)];

  if (uniqueEntities.length > 0) {
    uniqueEntities.sort((a, b) => a.localeCompare(b)).forEach((entity) => {
      const mentions = allReels.filter((r) => (r.entities || "").includes(entity));
      const first = mentions[0];
      const link = first?.url ? `[${first.subject || "Reel"}](${first.url})` : "Reel";
      md += `| **${entity}** | ${first?.domain || "General"} > ${first?.subdomain || "General"} | ${link} |\n`;
    });
  } else {
    md += `| *No tools extracted yet* | — | — |\n`;
  }

  md += `\n<br>\n\n<div align="center">\n  <sub>Generated by <strong><a href="${BRAND_URL}">${BRAND_NAME}</a></strong> • Turn Instagram Reels into Reusable Knowledge</sub>\n</div>\n`;

  return md;
}

/**
 * Exports all playbooks structured by Domain Folder & Subdomain File into ZIP array
 */
export async function exportAllPlaybooksAsZip() {
  return new Promise((resolve) => {
    chrome.storage.local.get({ reelsData: [] }, (result) => {
      const all = result.reelsData || [];
      if (!all.length) {
        resolve({ success: false, error: "No reels saved yet." });
        return;
      }

      // Group reels by Domain -> Subdomain
      const tree = {};
      all.forEach((r) => {
        const d = (r.domain || "General Insights").trim();
        const s = (r.subdomain || "General").trim();
        if (!tree[d]) tree[d] = {};
        if (!tree[d][s]) tree[d][s] = [];
        tree[d][s].push(r);
      });

      const files = [];

      // 1. Generate Domain/Subdomain .md files
      for (const [domain, subdomains] of Object.entries(tree)) {
        const cleanDom = sanitizeFileName(domain);
        for (const [subdomain, reels] of Object.entries(subdomains)) {
          const cleanSub = sanitizeFileName(subdomain);
          const relativePath = `${cleanDom}/${cleanSub}.md`;
          const content = buildSubdomainPlaybookMarkdown(domain, subdomain, reels);
          files.push({ filename: relativePath, content: content });
        }
      }

      // 2. Generate 00_Master_Index.md
      const indexContent = buildMasterIndexMarkdown(all, tree);
      files.unshift({ filename: "00_Master_Index.md", content: indexContent });

      resolve({
        success: true,
        files: files,
        totalFiles: files.length,
        totalReels: all.length
      });
    });
  });
}

/**
 * Legacy single-file export helper (CSV / JSON / Markdown)
 */
export async function exportData(format = "markdown") {
  return new Promise((resolve) => {
    chrome.storage.local.get({ reelsData: [] }, (result) => {
      const all = result.reelsData || [];
      if (!all.length) {
        resolve({ success: false, error: "No reels saved yet." });
        return;
      }

      const dateStr = new Date().toISOString().slice(0, 10);

      if (format === "csv") {
        let csv = "Timestamp,Domain,Subdomain,Subject,Personal Utility,Entities,Tags,URL,Summary\n";
        all.forEach((item) => {
          const cleanSummary = (item.summary || "").replace(/"/g, '""');
          const cleanDomain = (item.domain || "").replace(/"/g, '""');
          const cleanSubdomain = (item.subdomain || "").replace(/"/g, '""');
          const cleanSubject = (item.subject || "").replace(/"/g, '""');
          const cleanUtility = (item.personalUtility || "").replace(/"/g, '""');
          const cleanEntities = (item.entities || "").replace(/"/g, '""');
          const cleanTags = (item.tags || "").replace(/"/g, '""');
          csv += `"${item.date || item.timestamp || ""}","${cleanDomain}","${cleanSubdomain}","${cleanSubject}","${cleanUtility}","${cleanEntities}","${cleanTags}","${item.url || ""}","${cleanSummary}"\n`;
        });
        resolve({ success: true, content: csv, filename: `reels_knowledge_${dateStr}.csv` });
      } else if (format === "json") {
        resolve({
          success: true,
          content: JSON.stringify(all, null, 2),
          filename: `reels_knowledge_${dateStr}.json`
        });
      } else {
        const tree = {};
        all.forEach((r) => {
          const d = (r.domain || "General Insights").trim();
          const s = (r.subdomain || "General").trim();
          if (!tree[d]) tree[d] = {};
          if (!tree[d][s]) tree[d][s] = [];
          tree[d][s].push(r);
        });
        const md = buildMasterIndexMarkdown(all, tree);
        resolve({ success: true, content: md, filename: `reels_playbook_${dateStr}.md` });
      }
    });
  });
}

/**
 * Domain-specific single playbook generator
 */
export async function exportCategoryPlaybook(category, subdomain = "") {
  return new Promise((resolve) => {
    chrome.storage.local.get({ reelsData: [] }, (result) => {
      const all = result.reelsData || [];
      const filtered = all.filter((r) => {
        const d = r.domain || r.category || "General";
        if (subdomain) {
          return d.toLowerCase() === category.toLowerCase() && (r.subdomain || "").toLowerCase() === subdomain.toLowerCase();
        }
        return d.toLowerCase() === category.toLowerCase();
      });

      if (!filtered.length) {
        resolve({ success: false, error: `No reels saved in category "${category}".` });
        return;
      }

      const content = buildSubdomainPlaybookMarkdown(category, subdomain || "General", filtered);
      const safeCat = sanitizeFileName(category);
      const safeSub = subdomain ? `_${sanitizeFileName(subdomain)}` : "";

      resolve({
        success: true,
        content: content,
        filename: `${safeCat}${safeSub}_Playbook.md`,
        count: filtered.length
      });
    });
  });
}
