import { ReelItem } from '@/types';

const BRAND_URL = 'https://reelanalyzer.manikanta.co.in/';
const BRAND_NAME = 'Reel Analyzer';

function slugify(str: string): string {
  if (!str) return 'insight';
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export function generatePlaybookMarkdown(
  reels: ReelItem[],
  selectedDomain: string = 'All',
  selectedSubdomain: string = 'All'
): string {
  const filtered = reels.filter((item) => {
    const domainMatch = selectedDomain === 'All' || item.domain === selectedDomain;
    const subMatch = selectedSubdomain === 'All' || item.subdomain === selectedSubdomain;
    return domainMatch && subMatch;
  });

  const now = new Date().toISOString().slice(0, 10);
  const title = selectedDomain === 'All'
    ? `${BRAND_NAME} Knowledge Playbook (Master Collection)`
    : selectedSubdomain !== 'All'
      ? `${selectedDomain} > ${selectedSubdomain}`
      : `${selectedDomain} Playbook`;

  let md = `---
vault: "${BRAND_NAME}"
domain: "${selectedDomain}"
subdomain: "${selectedSubdomain}"
total_insights: ${filtered.length}
exported_at: "${now}"
source: "${BRAND_URL}"
---

# 📚 ${title}

> 🧠 **${BRAND_NAME} Knowledge Engine**
> Total Curated Insights: **${filtered.length} Reels**

---

## 📑 Table of Contents
`;

  filtered.forEach((item, index) => {
    const num = index + 1;
    const itemTitle = item.subject || `Insight #${num}`;
    const anchor = `${num}-${slugify(itemTitle)}`;
    const utility = item.personalUtility ? ` — *💡 ${item.personalUtility.slice(0, 90)}${item.personalUtility.length > 90 ? '...' : ''}*` : '';
    md += `${num}. [${itemTitle}](#${anchor})${utility}\n`;
  });

  md += `\n---\n\n`;

  // Group by Domain & Subdomain
  const grouped: { [domain: string]: { [subdomain: string]: ReelItem[] } } = {};
  filtered.forEach((item) => {
    const d = item.domain || 'Uncategorized';
    const s = item.subdomain || 'General Insights';
    if (!grouped[d]) grouped[d] = {};
    if (!grouped[d][s]) grouped[d][s] = [];
    grouped[d][s].push(item);
  });

  let globalIdx = 0;
  for (const [domain, subdomains] of Object.entries(grouped)) {
    md += `# 🌐 ${domain}\n\n`;
    for (const [subdomain, items] of Object.entries(subdomains)) {
      md += `## 📂 ${subdomain}\n\n`;
      items.forEach((item) => {
        globalIdx++;
        const itemTitle = item.subject || `Insight #${globalIdx}`;
        const anchor = `${globalIdx}-${slugify(itemTitle)}`;

        md += `### ${globalIdx}. ${itemTitle} <a id="${anchor}"></a>\n\n`;
        if (item.personalUtility) {
          md += `> 💡 **Key Takeaway:** ${item.personalUtility}\n`;
        }
        if (item.entities) {
          md += `> 🛠️ **Tools & Tech:** \`${item.entities}\`\n`;
        }
        if (item.tags) {
          md += `> 🏷️ **Tags:** ${item.tags}\n`;
        }
        md += `> 🔗 **Original Reel:** [Watch on Instagram](${item.url})\n\n`;

        md += `#### 📖 Summary & Directives\n\n${item.summary}\n\n`;
        md += `---\n\n`;
      });
    }
  }

  md += `<br>\n\n<div align="center">\n  <sub>Generated by <strong><a href="${BRAND_URL}">${BRAND_NAME}</a></strong> • Turn Instagram Reels into Reusable Knowledge</sub>\n</div>\n`;

  return md;
}

export function downloadMarkdownFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
