import { ReelItem } from '@/types';
import { formatDisplayDate } from './utils';

export function generatePlaybookMarkdown(
  reels: ReelItem[],
  selectedDomain: string = 'All',
  selectedSubdomain: string = 'All'
): string {
  const filtered = reels.filter((item) => {
    const domainMatch = selectedDomain === 'All' || item.domain === selectedDomain;
    const subMatch = selectedSubdomain === 'All' || item.subdomain === selectedSubdomain;
    return domainMatch && subMatch;
  });

  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# 📚 Knowledge Playbook: ${selectedDomain === 'All' ? 'Master Collection' : selectedDomain}\n`;
  if (selectedSubdomain !== 'All') {
    md += `### 📂 Subdomain Focus: ${selectedSubdomain}\n`;
  }
  md += `*Generated by Reel Analyzer Knowledge Engine • ${now} • Total Insights: ${filtered.length}*\n\n`;
  md += `---\n\n`;

  // Table of Contents
  md += `## 📑 Table of Contents\n`;
  filtered.forEach((item, index) => {
    const anchor = (item.subject || 'Insight')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    md += `${index + 1}. [${item.subject || 'Insight #' + (index + 1)}](#${anchor}) — *${item.domain} > ${item.subdomain || 'General'}*\n`;
  });
  md += `\n---\n\n`;

  // Group by Domain & Subdomain
  const grouped: { [domain: string]: { [subdomain: string]: ReelItem[] } } = {};
  filtered.forEach((item) => {
    const d = item.domain || 'Uncategorized';
    const s = item.subdomain || 'General Insights';
    if (!grouped[d]) grouped[d] = {};
    if (!grouped[d][s]) grouped[d][s] = [];
    grouped[d][s].push(item);
  });

  for (const [domain, subdomains] of Object.entries(grouped)) {
    md += `# 🌐 ${domain}\n\n`;
    for (const [subdomain, items] of Object.entries(subdomains)) {
      md += `## 📂 ${subdomain}\n\n`;
      items.forEach((item) => {
        md += `### ⚡ ${item.subject || 'Actionable Insight'}\n`;
        md += `- **Creator:** [@${item.author || 'unknown'}](${item.url})\n`;
        md += `- **Date:** ${formatDisplayDate(item.postedDate || item.date || item.timestamp)}\n`;
        if (item.personalUtility) {
          md += `- **💡 High-Value Utility:** ${item.personalUtility}\n`;
        }
        if (item.entities) {
          md += `- **🛠️ Tools & Entities:** \`${item.entities}\`\n`;
        }
        if (item.tags) {
          md += `- **🏷️ Tags:** ${item.tags}\n`;
        }
        md += `\n#### 📖 Summary & Directives\n\n${item.summary}\n\n`;
        md += `[🔗 View Original Reel](${item.url})\n\n`;
        md += `---\n\n`;
      });
    }
  }

  return md;
}

export function downloadMarkdownFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
